close all;
colormap default;
A = imread('umbrellas.jpg');
A_hist = myhist3(A,8);
A_bg = squeeze(sum(A_hist,1));
A_br = squeeze(sum(A_hist,2));
A_gr = squeeze(sum(A_hist,3));
figure(1); clf;
subplot(1,4,1);
imshow(A);
subplot(1,4,2);
bar3(A_bg);
xlabel("green");
ylabel("blue");
subplot(1,4,3);
bar3(A_br);
xlabel("red");
ylabel("blue");
subplot(1,4,4);
bar3(A_gr);
xlabel("red");
ylabel("green");